"""Added status

Revision ID: a475e5cfb9f5
Revises: 7db906ab42f6
Create Date: 2022-06-22 17:10:30.528946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475e5cfb9f5'
down_revision = '7db906ab42f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_statuses_name'))
    )
    op.add_column('reviews', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_reviews_status_id_statuses'), 'reviews', 'statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_status_id_statuses'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
